# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ mkplc-action ]
  pull_request:
    branches: [ mkplc-action ]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v2
            with:
              node-version: ${{ matrix.node-version }}
          - run: npm ci
          - run: npm run build --if-present
          - run: npm test
          - name: List Services
            uses: retgits/akkasls-action@v2
            with:
              cmd: "services list"
            env:
              token: ${{ secrets.AKKASLS_TOKEN }}
              project: ${{ secrets.AKKASLS_PROJECT_ID }}
